export const signGuides = [
  {
    name: "Aries",
    keyword: "Iniciativa",
    element: "Fuego",
    modality: "Cardinal",
    polarity: "Yang / activa",
    rulerTraditional: "Marte",
    rulerModern: "Marte",
    season: "Inicio de la primavera simbólica",
    archetype: "La chispa que abre camino",
    description: "Aries explora el deseo de comenzar, actuar y afirmar una identidad propia.",
    strengths: ["Coraje para iniciar", "Franqueza", "Capacidad de reacción"],
    tensions: ["Impaciencia", "Competencia automática", "Dificultad para sostener la espera"],
    questions: ["¿Qué merece ser iniciado ahora?", "¿Cómo actuar sin convertir cada diferencia en combate?"],
  },
  {
    name: "Tauro",
    keyword: "Sostén",
    element: "Tierra",
    modality: "Fijo",
    polarity: "Yin / receptiva",
    rulerTraditional: "Venus",
    rulerModern: "Venus",
    season: "Plenitud de la primavera simbólica",
    archetype: "El jardín que aprende a durar",
    description: "Tauro observa la relación con los recursos, el cuerpo y la capacidad de cultivar lo que tiene valor.",
    strengths: ["Perseverancia", "Sensibilidad corporal", "Lealtad a los valores"],
    tensions: ["Apego", "Resistencia al cambio", "Confundir seguridad con inmovilidad"],
    questions: ["¿Qué valor estoy construyendo con tiempo?", "¿Qué puedo soltar sin perder estabilidad?"],
  },
  {
    name: "Géminis",
    keyword: "Intercambio",
    element: "Aire",
    modality: "Mutable",
    polarity: "Yang / activa",
    rulerTraditional: "Mercurio",
    rulerModern: "Mercurio",
    season: "Transición hacia el verano simbólico",
    archetype: "El puente entre dos preguntas",
    description: "Géminis representa curiosidad, lenguaje y la habilidad de tejer conexiones entre ideas y personas.",
    strengths: ["Curiosidad", "Versatilidad", "Capacidad de traducir perspectivas"],
    tensions: ["Dispersión", "Exceso de estímulo", "Quedarse en la descripción"],
    questions: ["¿Qué conversación abre una comprensión nueva?", "¿Qué información necesita convertirse en experiencia?"],
  },
  {
    name: "Cáncer",
    keyword: "Raíz",
    element: "Agua",
    modality: "Cardinal",
    polarity: "Yin / receptiva",
    rulerTraditional: "Luna",
    rulerModern: "Luna",
    season: "Inicio del verano simbólico",
    archetype: "La memoria que protege una semilla",
    description: "Cáncer explora memoria, cuidado y la necesidad de construir un espacio emocionalmente seguro.",
    strengths: ["Cuidado", "Memoria afectiva", "Intuición del clima emocional"],
    tensions: ["Defensividad", "Nostalgia", "Cuidar sin pedir consentimiento"],
    questions: ["¿Qué significa pertenecer hoy?", "¿Cómo cuidar sin convertir el cuidado en control?"],
  },
  {
    name: "Leo",
    keyword: "Expresión",
    element: "Fuego",
    modality: "Fijo",
    polarity: "Yang / activa",
    rulerTraditional: "Sol",
    rulerModern: "Sol",
    season: "Plenitud del verano simbólico",
    archetype: "El corazón que se vuelve visible",
    description: "Leo habla de la voluntad creativa, el juego y el valor de hacer visible una voz propia.",
    strengths: ["Generosidad", "Creatividad", "Calor expresivo"],
    tensions: ["Necesidad de aprobación", "Dramatización", "Confundir reconocimiento con valor"],
    questions: ["¿Qué deseo crear aunque nadie aplauda?", "¿Cómo compartir el centro sin desaparecer ni ocuparlo todo?"],
  },
  {
    name: "Virgo",
    keyword: "Discernimiento",
    element: "Tierra",
    modality: "Mutable",
    polarity: "Yin / receptiva",
    rulerTraditional: "Mercurio",
    rulerModern: "Mercurio",
    season: "Transición hacia el otoño simbólico",
    archetype: "La artesana que mejora el instrumento",
    description: "Virgo orienta la atención hacia el oficio, los hábitos y los pequeños ajustes que mejoran la vida diaria.",
    strengths: ["Observación", "Oficio", "Capacidad de ordenar lo complejo"],
    tensions: ["Perfeccionismo", "Autocrítica", "Perder el conjunto por el detalle"],
    questions: ["¿Qué mejora pequeña tendría un efecto real?", "¿Qué estándar me ayuda y cuál me castiga?"],
  },
  {
    name: "Libra",
    keyword: "Vínculo",
    element: "Aire",
    modality: "Cardinal",
    polarity: "Yang / activa",
    rulerTraditional: "Venus",
    rulerModern: "Venus",
    season: "Inicio del otoño simbólico",
    archetype: "La balanza que busca una conversación justa",
    description: "Libra investiga el arte del encuentro, la reciprocidad y la búsqueda de equilibrio en las relaciones.",
    strengths: ["Diplomacia", "Sentido de proporción", "Capacidad de negociar"],
    tensions: ["Indecisión", "Evitar el conflicto", "Definir el deseo solo en relación con otro"],
    questions: ["¿Qué acuerdo sería justo para ambas partes?", "¿Qué verdad incómoda necesita entrar en la conversación?"],
  },
  {
    name: "Escorpio",
    keyword: "Profundidad",
    element: "Agua",
    modality: "Fijo",
    polarity: "Yin / receptiva",
    rulerTraditional: "Marte",
    rulerModern: "Plutón",
    season: "Plenitud del otoño simbólico",
    archetype: "La raíz que transforma lo enterrado",
    description: "Escorpio trata transformación, intimidad y la valentía de mirar lo que necesita renovarse.",
    strengths: ["Percepción profunda", "Resiliencia", "Compromiso con la verdad emocional"],
    tensions: ["Control", "Sospecha", "Quedarse unido a una herida"],
    questions: ["¿Qué necesita morir para que algo cambie de forma?", "¿Dónde puedo confiar sin renunciar a mis límites?"],
  },
  {
    name: "Sagitario",
    keyword: "Sentido",
    element: "Fuego",
    modality: "Mutable",
    polarity: "Yang / activa",
    rulerTraditional: "Júpiter",
    rulerModern: "Júpiter",
    season: "Transición hacia el invierno simbólico",
    archetype: "La flecha que busca horizonte",
    description: "Sagitario contempla visión, aprendizaje y el impulso de ampliar horizontes físicos o mentales.",
    strengths: ["Entusiasmo", "Visión", "Capacidad de aprender de la experiencia"],
    tensions: ["Exceso de certeza", "Prometer más de lo posible", "Confundir libertad con fuga"],
    questions: ["¿Qué convicción merece ser revisada?", "¿Qué viaje transforma mi manera de comprender?"],
  },
  {
    name: "Capricornio",
    keyword: "Estructura",
    element: "Tierra",
    modality: "Cardinal",
    polarity: "Yin / receptiva",
    rulerTraditional: "Saturno",
    rulerModern: "Saturno",
    season: "Inicio del invierno simbólico",
    archetype: "La montaña construida por etapas",
    description: "Capricornio aborda responsabilidad, tiempo y la construcción paciente de una meta significativa.",
    strengths: ["Disciplina", "Perspectiva de largo plazo", "Responsabilidad"],
    tensions: ["Rigidez", "Sobrecarga", "Medir el valor solo por resultados"],
    questions: ["¿Qué estructura sostiene de verdad mi propósito?", "¿Qué responsabilidad ya no me corresponde cargar?"],
  },
  {
    name: "Acuario",
    keyword: "Perspectiva",
    element: "Aire",
    modality: "Fijo",
    polarity: "Yang / activa",
    rulerTraditional: "Saturno",
    rulerModern: "Urano",
    season: "Plenitud del invierno simbólico",
    archetype: "La ventana que imagina otro futuro",
    description: "Acuario pone el foco en comunidad, innovación y la distancia necesaria para imaginar futuros distintos.",
    strengths: ["Pensamiento independiente", "Visión colectiva", "Innovación"],
    tensions: ["Distancia emocional", "Contradecir por sistema", "Idealizar la comunidad"],
    questions: ["¿Qué futuro estoy ayudando a construir?", "¿Cómo sostener singularidad y pertenencia a la vez?"],
  },
  {
    name: "Piscis",
    keyword: "Sensibilidad",
    element: "Agua",
    modality: "Mutable",
    polarity: "Yin / receptiva",
    rulerTraditional: "Júpiter",
    rulerModern: "Neptuno",
    season: "Transición hacia la primavera simbólica",
    archetype: "El umbral entre sueño y vigilia",
    description: "Piscis explora intuición, imaginación y la apertura a aquello que trasciende lo estrictamente racional.",
    strengths: ["Empatía", "Imaginación", "Capacidad de percibir matices"],
    tensions: ["Fronteras difusas", "Idealización", "Escapismo"],
    questions: ["¿Qué límite protege mi sensibilidad?", "¿Cómo convertir la imaginación en una práctica concreta?"],
  },
] as const;

export const planetaryGuides = [
  { symbol: "☉", name: "Sol", description: "Vitalidad, identidad y dirección consciente.", domains: "Centro, voluntad, creatividad y sentido de presencia.", constructive: "Ayuda a organizar una experiencia alrededor de un propósito y una voz propia.", shadow: "Puede convertirse en centralidad rígida o dependencia del reconocimiento.", questions: ["¿Qué deseo hacer visible?", "¿Qué dirección se siente propia?"], cycle: "Ciclo anual aparente alrededor del zodíaco.", references: ["nasa", "method"] },
  { symbol: "☽", name: "Luna", description: "Necesidades emocionales, hábitos y memoria.", domains: "Cuidado, pertenencia, ritmos corporales y respuesta instintiva.", constructive: "Permite reconocer necesidades y construir formas de seguridad emocional.", shadow: "Puede quedar atrapada en automatismos o reaccionar desde la defensa.", questions: ["¿Qué necesito para sentir sostén?", "¿Qué hábito emocional pide escucha?"], cycle: "Ciclo rápido, aproximadamente mensual en la tradición simbólica.", references: ["nasa", "method"] },
  { symbol: "☿", name: "Mercurio", description: "Lenguaje, pensamiento y formas de aprendizaje.", domains: "Percepción, conversación, análisis y movimiento de información.", constructive: "Facilita nombrar, conectar ideas y adaptar una explicación al contexto.", shadow: "Puede dispersarse, racionalizar lo afectivo o confundir velocidad con claridad.", questions: ["¿Qué necesito preguntar antes de concluir?", "¿Qué lenguaje hace posible el encuentro?"], cycle: "Órbita interior rápida y fases aparentes de retrogradación.", references: ["nasa", "method"] },
  { symbol: "♀", name: "Venus", description: "Afecto, gusto, placer y valores personales.", domains: "Reciprocidad, estética, deseo de armonía y relación con recursos.", constructive: "Ayuda a reconocer lo valioso y a construir acuerdos con sensibilidad.", shadow: "Puede buscar aprobación, evitar diferencias o medir el valor desde el agrado.", questions: ["¿Qué deseo cuidar y disfrutar?", "¿Qué valor no quiero negociar?"], cycle: "Ciclo aparente interior y relación periódica con el Sol.", references: ["nasa", "method"] },
  { symbol: "♂", name: "Marte", description: "Deseo, iniciativa y modo de defender límites.", domains: "Acción, impulso, conflicto, coraje y energía disponible.", constructive: "Permite actuar, cortar inercias y expresar un límite claro.", shadow: "Puede competir por reflejo o convertir tensión en agresión.", questions: ["¿Qué acción concreta expresa mi deseo?", "¿Cómo defender un límite sin destruir el vínculo?"], cycle: "Ciclo aparente de aproximadamente dos años.", references: ["nasa", "method"] },
  { symbol: "♃", name: "Júpiter", description: "Expansión, confianza y marcos de sentido.", domains: "Aprendizaje, viaje, filosofía, crecimiento y generosidad.", constructive: "Abre perspectivas y ayuda a encontrar significado en la experiencia.", shadow: "Puede exagerar, prometer demasiado o convertir una opinión en dogma.", questions: ["¿Qué creencia amplía mi mundo sin cerrarlo?", "¿Qué oportunidad necesita medida?"], cycle: "Ciclo aparente cercano a doce años.", references: ["nasa", "method"] },
  { symbol: "♄", name: "Saturno", description: "Límites, compromiso, práctica y maduración.", domains: "Tiempo, estructura, responsabilidad, autoridad y consecuencias.", constructive: "Ayuda a convertir una intención en una práctica sostenible.", shadow: "Puede endurecerse como miedo, culpa o exigencia sin descanso.", questions: ["¿Qué límite vuelve posible mi propósito?", "¿Qué compromiso necesita una forma más humana?"], cycle: "Ciclo aparente cercano a veintinueve años.", references: ["nasa", "method"] },
  { symbol: "♅", name: "Urano", description: "Cambio, independencia e innovación.", domains: "Ruptura, autonomía, tecnología y cambios de perspectiva.", constructive: "Introduce alternativas cuando una estructura ya no responde a la realidad.", shadow: "Puede confundir libertad con rechazo de todo vínculo o continuidad.", questions: ["¿Qué patrón pide una interrupción creativa?", "¿Qué parte de mi diferencia necesita integración?"], cycle: "Ciclo generacional largo, alrededor de ochenta y cuatro años.", references: ["nasa", "method"] },
  { symbol: "♆", name: "Neptuno", description: "Imaginación, empatía e ideales.", domains: "Sueño, arte, compasión, sensibilidad y disolución de fronteras.", constructive: "Amplía la imaginación y la capacidad de sentir interdependencia.", shadow: "Puede idealizar, confundir intuición con certeza o perder límites.", questions: ["¿Qué necesita una frontera más clara?", "¿Cómo aterrizar un ideal sin empobrecerlo?"], cycle: "Ciclo generacional largo, alrededor de ciento sesenta y cinco años.", references: ["nasa", "method"] },
  { symbol: "♇", name: "Plutón", description: "Poder, profundidad y procesos de transformación.", domains: "Crisis, duelo, intensidad, regeneración y relación con lo oculto.", constructive: "Invita a transformar estructuras de poder y recuperar energía propia.", shadow: "Puede intensificar el control, la compulsión o la lógica de todo o nada.", questions: ["¿Qué forma de poder necesita hacerse consciente?", "¿Qué puedo transformar sin negar lo vivido?"], cycle: "Ciclo generacional muy largo y variable.", references: ["nasa", "method"] },
] as const;

export const housesGuide = [
  { number: 1, topic: "Presencia e iniciativa", axis: "Yo / presencia", keywords: ["Identidad", "cuerpo", "comienzo"], description: "La manera de entrar en una situación y de ser percibido; en casas iguales comienza en el ascendente.", questions: ["¿Cómo inicio?", "¿Qué imagen corporal y actitud llevo al mundo?"] },
  { number: 2, topic: "Recursos y valores", axis: "Yo / sostén", keywords: ["Recursos", "valores", "autovalor"], description: "Relación con recursos, habilidades, dinero, cuerpo y aquello que se considera valioso.", questions: ["¿Qué sé sostener?", "¿Qué valor no depende de la posesión?"] },
  { number: 3, topic: "Comunicación y entorno", axis: "Yo / intercambio", keywords: ["Lenguaje", "aprendizaje", "cercanía"], description: "Pensamiento cotidiano, conversaciones, aprendizaje básico, desplazamientos y entorno próximo.", questions: ["¿Qué necesito nombrar?", "¿Qué información conecta mi mundo cercano?"] },
  { number: 4, topic: "Raíces y pertenencia", axis: "Privado / público", keywords: ["Hogar", "origen", "intimidad"], description: "Base emocional, hogar, raíces, memoria y la sensación de tener un lugar propio.", questions: ["¿Qué llamo hogar?", "¿Qué herencia deseo transformar?"] },
  { number: 5, topic: "Creatividad y disfrute", axis: "Expresión / servicio", keywords: ["Juego", "deseo", "creación"], description: "Placer, juego, creatividad, romance, expresión individual y capacidad de celebrar la vida.", questions: ["¿Qué hago por puro deseo?", "¿Dónde permito que mi creatividad tenga riesgo?"] },
  { number: 6, topic: "Hábitos y servicio", axis: "Expresión / servicio", keywords: ["Rutina", "salud cotidiana", "oficio"], description: "Ritmos diarios, trabajo concreto, hábitos, cuidado práctico y relación con la mejora continua.", questions: ["¿Qué rutina me devuelve energía?", "¿Qué servicio puedo prestar sin desaparecer?"] },
  { number: 7, topic: "Vínculos y acuerdos", axis: "Yo / otro", keywords: ["Pareja", "contrato", "reflejo"], description: "Relaciones de igual a igual, acuerdos, sociedades y la forma de encontrarse con un otro significativo.", questions: ["¿Qué proyecto en el otro?", "¿Qué acuerdo necesita reciprocidad real?"] },
  { number: 8, topic: "Intimidad y transformación", axis: "Yo / otro", keywords: ["Confianza", "recursos compartidos", "duelo"], description: "Intimidad, intercambio de recursos, crisis, confianza y procesos de transformación compartida.", questions: ["¿Qué comparto y bajo qué condiciones?", "¿Qué transformación no puedo hacer en soledad?"] },
  { number: 9, topic: "Sentido y exploración", axis: "Cercanía / horizonte", keywords: ["Viaje", "estudio", "cosmovisión"], description: "Viajes lejanos, estudios superiores, filosofía, creencias y búsqueda de un horizonte de sentido.", questions: ["¿Qué experiencia ensancha mi marco?", "¿Qué convicción acepta ser cuestionada?"] },
  { number: 10, topic: "Vocación y proyección", axis: "Privado / público", keywords: ["Vocación", "reputación", "dirección"], description: "Dirección pública, vocación, autoridad, metas y la huella que se desea dejar en el mundo.", questions: ["¿Qué responsabilidad pública elijo?", "¿Cómo defino éxito sin repetir un mandato?"] },
  { number: 11, topic: "Comunidad y futuro", axis: "Expresión / comunidad", keywords: ["Amistad", "red", "futuro"], description: "Amistades, comunidades, redes, proyectos colectivos y futuros que se imaginan con otros.", questions: ["¿Qué comunidad me vuelve más capaz?", "¿Qué futuro construyo en plural?"] },
  { number: 12, topic: "Mundo interior y cierre", axis: "Cercanía / horizonte", keywords: ["Retiro", "sueño", "integración"], description: "Retiro, inconsciente simbólico, descanso, límites porosos y procesos de cierre e integración.", questions: ["¿Qué necesita silencio?", "¿Qué puedo integrar sin exigir una respuesta inmediata?"] },
] as const;

export const aspectsGuide = [
  { symbol: "☌", name: "Conjunción", angle: "0°", description: "Fusión de dos funciones en el mismo punto del zodíaco.", constructive: "Concentra energía y vuelve muy visible el tema combinado.", challenge: "Puede ser difícil separar necesidades o reconocer alternativas.", questions: ["¿Cómo trabajan juntas estas funciones?", "¿Qué necesita una salida propia?"] },
  { symbol: "⚹", name: "Sextil", angle: "60°", description: "Puente de 60° que facilita colaboración y aprendizaje.", constructive: "Ofrece una oportunidad que crece cuando se practica de forma intencional.", challenge: "La facilidad puede pasar desapercibida si no se activa.", questions: ["¿Qué recurso está disponible?", "¿Qué práctica convierte potencial en habilidad?"] },
  { symbol: "□", name: "Cuadratura", angle: "90°", description: "Tensión de 90° que pide acción y reajuste.", constructive: "Moviliza decisiones y obliga a crear una solución más compleja.", challenge: "Puede vivirse como bloqueo, presión o conflicto repetido.", questions: ["¿Qué dos necesidades reclaman espacio?", "¿Qué acción reduce la fricción sin negar el conflicto?"] },
  { symbol: "△", name: "Trígono", angle: "120°", description: "Fluidez de 120° entre energías de un mismo elemento.", constructive: "Facilita expresión y confianza en un registro conocido.", challenge: "Lo fácil puede quedarse sin dirección o darse por garantizado.", questions: ["¿Qué talento necesita disciplina?", "¿Cómo compartir esta fluidez con el entorno?"] },
  { symbol: "⚻", name: "Quincuncio", angle: "150°", description: "Ángulo de 150° que señala la necesidad de adaptación.", constructive: "Invita a ajustar hábitos y a integrar lenguajes que no encajan de inmediato.", challenge: "Puede sentirse como incomodidad difusa o demanda constante de corrección.", questions: ["¿Qué parte de mí opera con otra lógica?", "¿Qué ajuste es suficiente por ahora?"] },
  { symbol: "☍", name: "Oposición", angle: "180°", description: "Polaridad de 180° que se expresa a través de vínculos o contrastes.", constructive: "Hace visible una tensión complementaria que puede negociarse.", challenge: "Puede proyectar en el otro lo que todavía no se reconoce propio.", questions: ["¿Qué espejo ofrece este vínculo?", "¿Cómo sostener ambos polos sin elegir una caricatura?"] },
] as const;

export const deepDiveGuides = [
  {
    number: "01",
    title: "La gramática de una carta",
    subtitle: "Planeta · signo · casa · aspecto",
    body: "Una lectura integrada comienza por distinguir cuatro preguntas. El planeta señala la función simbólica; el signo, el modo en que se expresa; la casa, el ámbito donde gana protagonismo; y el aspecto, la relación geométrica con otros puntos. Ninguna pieza se interpreta de forma aislada: una Luna en un signo no dice lo mismo si cambia de casa o forma una oposición estrecha.",
    note: "Sugerencia de lectura: empieza por Sol, Luna, Ascendente y regentes de las casas angulares antes de recorrer todos los detalles.",
  },
  {
    number: "02",
    title: "El zodíaco como mapa",
    subtitle: "Doce sectores de treinta grados",
    body: "El zodíaco tropical organiza una franja de la eclíptica en doce segmentos iguales. Es una convención geométrica e histórica: los signos funcionan como divisiones de 30°, mientras las constelaciones visibles ocupan extensiones desiguales. Esta diferencia ayuda a leer los símbolos con precisión y evita confundir lenguaje astrológico con cartografía estelar.",
    note: "La historia de esta división enlaza observación celeste, calendario y cálculo mesopotámico; por eso una carta se basa en grados y no en la forma aparente de una constelación.",
  },
  {
    number: "03",
    title: "Casas y horizonte",
    subtitle: "Por qué importan la hora y el lugar",
    body: "Las casas convierten la posición celeste en una perspectiva local. El ascendente marca el punto que emerge por el horizonte oriental y organiza los sectores posteriores. En AstroNexo se usa una división de casas iguales: cada casa abarca 30° desde el ascendente. Esta elección ofrece una lectura consistente y transparente, aunque existan otros sistemas de casas en la práctica astrológica.",
    note: "Si la hora de nacimiento es aproximada, el ascendente y las casas pueden variar de manera significativa. Es mejor tratar esos resultados como hipótesis de trabajo.",
  },
  {
    number: "04",
    title: "Aspectos: la geometría del diálogo",
    subtitle: "Orbe, distancia y contexto",
    body: "Un aspecto describe una separación angular entre dos puntos. Conjunción, sextil, cuadratura, trígono y oposición no son etiquetas buenas o malas: muestran estilos distintos de integración, fricción, apoyo o polaridad. El orbe mide qué tan cerca está la distancia real del ángulo exacto; cuanto más estrecho, mayor es el énfasis que AstroNexo da al contacto dentro de la visualización.",
    note: "La cualidad de un aspecto cambia según los planetas, casas y signos implicados. Una cuadratura puede movilizar una decisión; un trígono puede mostrar una facilidad que necesita dirección consciente.",
  },
  {
    number: "05",
    title: "Tránsitos y movimiento aparente",
    subtitle: "El cielo actual frente a la carta natal",
    body: "Un tránsito compara las longitudes de los cuerpos en el presente con las posiciones de nacimiento. En términos astronómicos, las posiciones se calculan para una fecha, una hora y un punto de observación; en términos astrológicos, el contacto se utiliza como lenguaje simbólico para observar ritmos, temas y cambios de foco. No es una predicción cerrada ni una instrucción.",
    note: "Conviene observar duración y repetición: los planetas personales cambian rápido, mientras los lentos sostienen climas más extensos y suelen tocar a una generación completa.",
  },
  {
    number: "06",
    title: "Retornos, ciclos y comparación",
    subtitle: "Técnicas para una lectura responsable",
    body: "El retorno solar busca el instante en que el Sol alcanza nuevamente la longitud eclíptica natal. La sinastría, en cambio, coloca dos cartas en diálogo y revisa contactos entre ambas. Son técnicas diferentes: el retorno ofrece una imagen simbólica anual; la sinastría observa patrones relacionales. En ambos casos, el contexto humano y la autonomía de las personas pesan más que una puntuación o una frase aislada.",
    note: "Usa las herramientas para formular preguntas y reconocer ritmos. Evita convertirlas en diagnósticos, certezas o sustitutos de decisiones informadas.",
  },
] as const;

export const sourceGuides = [
  { id: "nasa", title: "NASA GSFC", category: "Astronomía y eclíptica", text: "Explicación educativa de la eclíptica, la franja zodiacal y la diferencia entre constelaciones visibles y signos usados en horóscopos. Página archivada; se consulta como material educativo.", href: "https://pwg.gsfc.nasa.gov/stargaze/Secliptc.htm" },
  { id: "history", title: "National Geographic", category: "Historia cultural", text: "Contexto sobre Mesopotamia, Babilonia, Grecia, el zodíaco de doce signos y la evolución de los horóscopos individualizados.", href: "https://www.nationalgeographic.com/history/article/history-of-horoscopes" },
  { id: "jpl", title: "NASA JPL Horizons", category: "Efemérides astronómicas", text: "Manual institucional para posiciones, movimiento y observabilidad de cuerpos del sistema solar con parámetros reproducibles.", href: "https://ssd.jpl.nasa.gov/horizons/manual.html" },
  { id: "method", title: "Astronomy Engine", category: "Método de cálculo", text: "Documentación del motor usado por AstroNexo para posiciones planetarias y conversiones de coordenadas eclípticas.", href: "https://github.com/cosinekitty/astronomy" },
  { id: "swiss", title: "Swiss Ephemeris", category: "Efemérides y marcos", text: "Descripción técnica de efemérides basadas en JPL y de las transformaciones hacia coordenadas usadas en herramientas astrológicas.", href: "https://www.astro.com/swisseph/swephinfo_e.htm" },
] as const;

export const sourceById = Object.fromEntries(sourceGuides.map((source) => [source.id, source])) as Record<string, (typeof sourceGuides)[number]>;
