import { useState } from "react";
import { BookOpenText, ExternalLink, Orbit, ScrollText } from "lucide-react";
import { ToolLayout } from "@/components/ToolLayout";
import { ZODIAC } from "@/lib/astrology";
import { aspectsGuide, deepDiveGuides, housesGuide, planetaryGuides, signGuides, sourceGuides } from "@/lib/editorial";

const tabs = ["Signos", "Planetas", "Casas", "Aspectos", "Lecturas", "Fuentes"] as const;
type Tab = typeof tabs[number];

export default function Guide() {
  const [active, setActive] = useState<Tab>("Signos");
  return <ToolLayout eyebrow="Guía astrológica" title="Un vocabulario para mirar el cielo" intro="Una biblioteca original para ir más allá de las definiciones: símbolos, geometría, ciclos y criterios para leer una carta con contexto.">
    <section className="guide-shell"><aside className="guide-nav"><span className="eyebrow"><BookOpenText size={14} /> Biblioteca</span><h2>Seis capas<br />del mapa.</h2>{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={active === tab ? "guide-tab guide-tab--active" : "guide-tab"}><span>{tab}</span><b>{String(tabs.indexOf(tab) + 1).padStart(2, "0")}</b></button>)}</aside><div className="guide-content">{active === "Signos" && <SignsContent />}{active === "Planetas" && <PlanetsContent />}{active === "Casas" && <HousesContent />}{active === "Aspectos" && <AspectsContent />}{active === "Lecturas" && <DeepDiveContent />}{active === "Fuentes" && <SourcesContent />}</div></section>
  </ToolLayout>;
}

function SignsContent() { return <><div className="guide-content__heading"><span className="eyebrow">Los doce signos</span><h2>Doce cualidades de expresión</h2><p>Un signo no agota a una persona. En una carta, describe el estilo que adopta un planeta o un punto determinado.</p></div><div className="sign-grid">{signGuides.map((sign, index) => <article className="sign-card" key={sign.name}><span>{ZODIAC[index]?.symbol}</span><small>{sign.element} · {sign.modality}</small><h3>{sign.name}</h3><strong>{sign.keyword}</strong><p>{sign.description}</p></article>)}</div></>; }
function PlanetsContent() { return <><div className="guide-content__heading"><span className="eyebrow">Planetas</span><h2>Funciones que se mueven</h2><p>En astrología, los planetas representan funciones psicológicas y ritmos de experiencia dentro del mapa.</p></div><div className="planet-guide">{planetaryGuides.map((planet) => <article key={planet.name}><span>{planet.symbol}</span><div><h3>{planet.name}</h3><p>{planet.description}</p></div></article>)}</div></>; }
function HousesContent() { return <><div className="guide-content__heading"><span className="eyebrow">Las casas</span><h2>Doce ámbitos de experiencia</h2><p>Las casas sitúan los símbolos en sectores de la vida. En AstroNexo se presentan en sistema de casas iguales desde el ascendente.</p></div><div className="houses-grid">{housesGuide.map((house) => <article key={house.number}><span>{String(house.number).padStart(2, "0")}</span><div className="house-arc" /><h3>Casa {house.number}</h3><p>{house.topic}</p></article>)}</div></>; }
function AspectsContent() { return <><div className="guide-content__heading"><span className="eyebrow"><Orbit size={14} /> Aspectos</span><h2>La relación entre dos puntos</h2><p>Los aspectos son distancias angulares. Ayudan a observar cómo dos funciones se combinan, cooperan o se desafían.</p></div><div className="aspect-guide">{aspectsGuide.map((aspect) => <article key={aspect.name}><span>{aspect.symbol}</span><div><h3>{aspect.name}</h3><p>{aspect.description}</p></div></article>)}</div></>; }
function DeepDiveContent() { return <><div className="guide-content__heading"><span className="eyebrow"><ScrollText size={14} /> Lecturas esenciales</span><h2>Aprender a leer sin simplificar</h2><p>Estas notas articulan conceptos técnicos y simbólicos en un lenguaje claro. Están redactadas por AstroNexo y sirven para acompañar, no reemplazar, tu propio criterio.</p></div><div className="deep-dive-grid">{deepDiveGuides.map((guide) => <article key={guide.number}><span>{guide.number}</span><small>{guide.subtitle}</small><h3>{guide.title}</h3><p>{guide.body}</p><div><b>Nota de lectura</b><em>{guide.note}</em></div></article>)}</div></>; }
function SourcesContent() { return <><div className="guide-content__heading"><span className="eyebrow"><BookOpenText size={14} /> Referencias</span><h2>Cómo construimos esta biblioteca</h2><p>AstroNexo separa los datos astronómicos calculables de los marcos de interpretación astrológica. Las referencias aportan contexto histórico y técnico; los textos del sitio son originales y no reproducen contenido de terceros.</p></div><div className="source-guide">{sourceGuides.map((source) => <a key={source.title} href={source.href} target="_blank" rel="noreferrer"><span>{source.category}</span><h3>{source.title} <ExternalLink size={14} /></h3><p>{source.text}</p><b>Consultar fuente</b></a>)}</div><aside className="editorial-principle"><span>✦</span><p><strong>Principio editorial.</strong> La astrología se presenta aquí como un lenguaje simbólico y cultural. Las posiciones celestes proceden de cálculos astronómicos; su lectura no es una afirmación científica ni un sustituto de asesoramiento profesional.</p></aside></>; }
